# Generated by Django 5.2.1 on 2025-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_review', 'In Review'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('published', 'Published')], default='upcoming', max_length=20)),
                ('date_of_meeting', models.DateField()),
                ('start_time', models.TimeField()),
                ('meeting_url', models.URLField(max_length=500)),
            ],
        ),
    ]
